# Site settings
title: Ned Ellis
baseurl: "http://nedellis.com"
url: "http://nedellis.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
